version: '3.8'
services:
  mysql-db:
    container_name: mysql-db
    image: mysql:8.0
    # build: .
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: Modular_App
      MYSQL_ROOT_PASSWORD: Modular_App
    ports:
      - 3306:3306

networks: 
  default:
    external:
      name: modular_app_network